/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
add_1_svc(numbers *argp, struct svc_req *rqstp,square)
{
	static int  result;
	
	square = argp->a * argp->a;
	printf("pow(%d) is called\n",argp->a,square);
      //  result = argp->a * argp->b;

	return &result;
}
